name: Push to ECR and Update ECS

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: game-sys-test-task
  ECS_CLUSTER: Cluster_dev
  ECS_SERVICE: game-sys-test-taskdev_service

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::988182271356:role/ecr_pusher_repo_game-sys-test-task
          aws-region:  ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and Push
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: $ECR_REPOSITORY
          IMAGE_TAG: ${{ github.sha }} 
        run: |
          docker build -t $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $REGISTRY/$ECR_REPOSITORY:latest
          
          docker push $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$ECR_REPOSITORY:latest
          
      - name: Configure AWS credentials for ECS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::988182271356:role/ecs_deployer_role_game-sys-test-task
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Update ECS Service
        run: |
          echo "Checking if ECS Service exists..."
          SERVICE_STATUS=$(aws ecs describe-services --cluster ${{ env.ECS_CLUSTER }} --services ${{ env.ECS_SERVICE }} --query "services[0].status" --output text 2>&1 || true)
          
          if [ "$SERVICE_STATUS" == "ACTIVE" ]; then
            echo "Service is ACTIVE. Triggering new deployment..."
            aws ecs update-service \
              --cluster ${{ env.ECS_CLUSTER }} \
              --service ${{ env.ECS_SERVICE }} \
              --force-new-deployment \
              --region ${{ env.AWS_REGION }} \
              --query "service.deployments[?status=='PRIMARY'].{ID:id, Status:status, CreatedAt:createdAt}" \
              --output table
          else
            echo "Service not found or not active (Status: $SERVICE_STATUS). Skipping update. Terraform will create it on next apply."
          fi
